[package]
name = "Planner"
version = "0.1.0"
authors = ["Adam Boguszewski <ab417730@students.mimuw.edu.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
