name: Rust
defaults:
  run:
    working-directory: src

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  fmt:
  
    runs-on: ubuntu-latest
    name: Rustfmt
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - run: cargo fmt --all -- --check
      
  clippy:
    
    runs-on: ubuntu-latest
    name: Clippy
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy
    - run: cargo clippy -- -D warnings  
